### ISSUE TITLE
More model support

### ISSUE THREAD

**Issue by kaishijeng** [thuyngch/ATSS-EfficientDet-PyTorch#1]
Do you plan to add D1-D7 models?

Thanks,

**Comment by thuyngch** [comment]
Hi @kaishijeng ,

I will add config files for D0-D7.
Regarding training, due to the limit of hardware, I just train and release D0 and D1.
If anyone can train larger versions (D2-D7), it would be great!

**Comment by kaishijeng** [comment]
I have one RTX 2080 and not sure it can train D2-D7. Will try it when you release it.
Are you going to release your trained models, D0 and D1?

Thanks,

**Comment by thuyngch** [comment]
Yeah,

I released D0, please check the readme.md ;)

**Comment by kaishijeng** [comment]
I saw it and thanks.
How many epochs have you train on D0?

Thanks,

**Comment by thuyngch** [comment]
I train 300 epochs as being reported in the EfficientDet paper.
You can see more detail in the config file: https://github.com/thuyngch/ATSS-EfficientDet-PyTorch/blob/master/configs/effdet/atss_effdet_d0.py
