### ISSUE TITLE
training custom dataset problem

### ISSUE THREAD

**Issue by betterhalfwzm** [thuyngch/ATSS-EfficientDet-PyTorch#2]
gt_masks_ann.append(ann['segmentation'])
KeyError: 'segmentation'

**Comment by thuyngch** [comment]
Hi @betterhalfwzm ,

Maybe your custom dataset does not have the field 'segmentation' as in COCO json format.
You can simply remove this field from code.

**Comment by betterhalfwzm** [comment]
> Hi @betterhalfwzm ,
> 
> Maybe your custom dataset does not have the field 'segmentation' as in COCO json format.
> You can simply remove this field from code.

Thank you for your prompt response and exciting code. Let me try. Do you have any other suggestions for training custom dataset or how can i set in config?
![image](https://user-images.githubusercontent.com/20449990/79533796-5e6a2900-80ab-11ea-99fe-2c8a7e8ba370.png)
![image](https://user-images.githubusercontent.com/20449990/79533920-bf91fc80-80ab-11ea-8ff9-cd1c21ec9a3b.png)

**Comment by betterhalfwzm** [comment]
> Hi @betterhalfwzm ,
> 
> Maybe your custom dataset does not have the field 'segmentation' as in COCO json format.
> You can simply remove this field from code.

It works, but  loss_cls: nan
/home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
/home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
2020-04-17 13:04:36,691 - mmdet - INFO - Epoch [1][50/4553]     lr: 0.00428, eta: 50 days, 21:20:20, time: 3.219, data_time: 2.560, memory: 8367, loss_cls: nan, loss_bbox: nan, loss_centerness: nan, loss: nan
2020-04-17 13:05:04,312 - mmdet - INFO - Epoch [1][100/4553]    lr: 0.00864, eta: 29 days, 19:26:31, time: 0.552, data_time: 0.010, memory: 8367, loss_cls: nan, loss_bbox: nan, loss_centerness: nan, loss: nan
@thuyngch

**Comment by thuyngch** [comment]
Hi @betterhalfwzm ,

I fixed the issue related to 'segmentation' field for you. Please check it here: https://github.com/thuyngch/ATSS-EfficientDet-PyTorch/commit/3f734f5ae328bf0be75aa58a745f498a2500a0ea

**Comment by thuyngch** [comment]
> > Hi @betterhalfwzm ,
> > Maybe your custom dataset does not have the field 'segmentation' as in COCO json format.
> > You can simply remove this field from code.
> 
> It works, but loss_cls: nan
> /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> 2020-04-17 13:04:36,691 - mmdet - INFO - Epoch [1][50/4553] lr: 0.00428, eta: 50 days, 21:20:20, time: 3.219, data_time: 2.560, memory: 8367, loss_cls: nan, loss_bbox: nan, loss_centerness: nan, loss: nan
> 2020-04-17 13:05:04,312 - mmdet - INFO - Epoch [1][100/4553] lr: 0.00864, eta: 29 days, 19:26:31, time: 0.552, data_time: 0.010, memory: 8367, loss_cls: nan, loss_bbox: nan, loss_centerness: nan, loss: nan
> @thuyngch

How many batchsize and GPUs did you set? 
If batchsize*GPUs=16n, set lr_start=ne-2.
For example, if batchsize*GPUs=32=16*2, then set lr_start=2e-2.

**Comment by betterhalfwzm** [comment]
> Hi @betterhalfwzm ,
> 
> I fixed the issue related to 'segmentation' field for you. Please check it here: [3f734f5](https://github.com/thuyngch/ATSS-EfficientDet-PyTorch/commit/3f734f5ae328bf0be75aa58a745f498a2500a0ea)
谢谢！！我现在数据只有一类，num_classes=2, 但是我的类别是1，我需要转为0吗？
@thuyngch

**Comment by thuyngch** [comment]
> > Hi @betterhalfwzm ,
> > I fixed the issue related to 'segmentation' field for you. Please check it here: [3f734f5](https://github.com/thuyngch/ATSS-EfficientDet-PyTorch/commit/3f734f5ae328bf0be75aa58a745f498a2500a0ea)
> > 谢谢！！我现在数据只有一类，num_classes=2, 但是我的类别是1，我需要转为0吗？
> > @thuyngch

Please use English!

**Comment by betterhalfwzm** [comment]
> > > Hi @betterhalfwzm ,
> > > I fixed the issue related to 'segmentation' field for you. Please check it here: [3f734f5](https://github.com/thuyngch/ATSS-EfficientDet-PyTorch/commit/3f734f5ae328bf0be75aa58a745f498a2500a0ea)
> > > 谢谢！！我现在数据只有一类，num_classes=2, 但是我的类别是1，我需要转为0吗？
> > > @thuyngch
> 
> Please use English!

Thank you!! Now I have only one class of data, num_classes = 2, but my class is id is 1. Do I need to change to 0?

**Comment by betterhalfwzm** [comment]
> > > Hi @betterhalfwzm ,
> > > Maybe your custom dataset does not have the field 'segmentation' as in COCO json format.
> > > You can simply remove this field from code.
> > 
> > 
> > It works, but loss_cls: nan
> > /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> > warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> > /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> > warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> > /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> > warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> > /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> > warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> > 2020-04-17 13:04:36,691 - mmdet - INFO - Epoch [1][50/4553] lr: 0.00428, eta: 50 days, 21:20:20, time: 3.219, data_time: 2.560, memory: 8367, loss_cls: nan, loss_bbox: nan, loss_centerness: nan, loss: nan
> > 2020-04-17 13:05:04,312 - mmdet - INFO - Epoch [1][100/4553] lr: 0.00864, eta: 29 days, 19:26:31, time: 0.552, data_time: 0.010, memory: 8367, loss_cls: nan, loss_bbox: nan, loss_centerness: nan, loss: nan
> > @thuyngch
> 
> How many batchsize and GPUs did you set?
> If batchsize_GPUs=16n, set lr_start=ne-2. For example, if batchsize_GPUs=32=16*2, then set lr_start=2e-2.

4 gpus ，imgs_per_gpu = 16

**Comment by thuyngch** [comment]
> > > > Hi @betterhalfwzm ,
> > > > I fixed the issue related to 'segmentation' field for you. Please check it here: [3f734f5](https://github.com/thuyngch/ATSS-EfficientDet-PyTorch/commit/3f734f5ae328bf0be75aa58a745f498a2500a0ea)
> > > > 谢谢！！我现在数据只有一类，num_classes=2, 但是我的类别是1，我需要转为0吗？
> > > > @thuyngch
> > 
> > 
> > Please use English!
> 
> Thank you!! Now I have only one class of data, num_classes = 2, but my class is id is 1. Do I need to change to 0?

No need to change ;)

**Comment by thuyngch** [comment]
> > > > Hi @betterhalfwzm ,
> > > > Maybe your custom dataset does not have the field 'segmentation' as in COCO json format.
> > > > You can simply remove this field from code.
> > > 
> > > 
> > > It works, but loss_cls: nan
> > > /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> > > warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> > > /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> > > warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> > > /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> > > warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> > > /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> > > warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> > > 2020-04-17 13:04:36,691 - mmdet - INFO - Epoch [1][50/4553] lr: 0.00428, eta: 50 days, 21:20:20, time: 3.219, data_time: 2.560, memory: 8367, loss_cls: nan, loss_bbox: nan, loss_centerness: nan, loss: nan
> > > 2020-04-17 13:05:04,312 - mmdet - INFO - Epoch [1][100/4553] lr: 0.00864, eta: 29 days, 19:26:31, time: 0.552, data_time: 0.010, memory: 8367, loss_cls: nan, loss_bbox: nan, loss_centerness: nan, loss: nan
> > > @thuyngch
> > 
> > 
> > How many batchsize and GPUs did you set?
> > If batchsize_GPUs=16n, set lr_start=ne-2. For example, if batchsize_GPUs=32=16*2, then set lr_start=2e-2.
> 
> 4 gpus ，imgs_per_gpu = 16

So set lr_start=4e-2

**Comment by betterhalfwzm** [comment]
> > > > > Hi @betterhalfwzm ,
> > > > > Maybe your custom dataset does not have the field 'segmentation' as in COCO json format.
> > > > > You can simply remove this field from code.
> > > > 
> > > > 
> > > > It works, but loss_cls: nan
> > > > /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> > > > warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> > > > /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> > > > warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> > > > /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> > > > warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> > > > /home/wangzhaoming/anaconda3/envs/torch1.4/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py:101: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
> > > > warnings.warn("torch.distributed.reduce_op is deprecated, please use "
> > > > 2020-04-17 13:04:36,691 - mmdet - INFO - Epoch [1][50/4553] lr: 0.00428, eta: 50 days, 21:20:20, time: 3.219, data_time: 2.560, memory: 8367, loss_cls: nan, loss_bbox: nan, loss_centerness: nan, loss: nan
> > > > 2020-04-17 13:05:04,312 - mmdet - INFO - Epoch [1][100/4553] lr: 0.00864, eta: 29 days, 19:26:31, time: 0.552, data_time: 0.010, memory: 8367, loss_cls: nan, loss_bbox: nan, loss_centerness: nan, loss: nan
> > > > @thuyngch
> > > 
> > > 
> > > How many batchsize and GPUs did you set?
> > > If batchsize_GPUs=16n, set lr_start=ne-2. For example, if batchsize_GPUs=32=16*2, then set lr_start=2e-2.
> > 
> > 
> > 4 gpus ，imgs_per_gpu = 16
> 
> So set lr_start=4e-2

lr_end = ?

**Comment by thuyngch** [comment]
You can set lr_end = lr_start/100 as using in the official mmdetection.
However, it could be 1e-4.
Try to test it!

**Comment by betterhalfwzm** [comment]
> You can set lr_end = lr_start/100 as using in the official mmdetection.
> However, it could be 1e-4.
> Try to test it!

Thanks again. I've trained successfully. Expected results！
