### ISSUE TITLE
Error when running your d0 pretrained model

### ISSUE THREAD

**Issue by kaishijeng** [thuyngch/ATSS-EfficientDet-PyTorch#3]
Got an error below when running python tools/test_single_image.py. The model is your pretrained d0 model.

/home/amd/USB/ATSS-EfficientDet-PyTorch/mmdet/ops/conv_module.py:68: UserWarning: ConvModule has norm and bias at the same time
  warnings.warn('ConvModule has norm and bias at the same time')
Traceback (most recent call last):
  File "tools/test_single_image.py", line 37, in <module>
    model = init_detector(config, checkpoint=checkpoint, device='cuda')
  File "/home/amd/USB/ATSS-EfficientDet-PyTorch/mmdet/apis/inference.py", line 37, in init_detector
    if 'CLASSES' in checkpoint['meta']:
KeyError: 'meta'

**Comment by thuyngch** [comment]
Hi @kaishijeng 

I fixed it.
Please check it here: https://github.com/thuyngch/ATSS-EfficientDet-PyTorch/commit/2e3062e9607469b9fbd87317c5519cf01817e9c8
