### ISSUE TITLE
Training time: How long does it take for training D0/D1?

### ISSUE THREAD

**Issue by yukitsuji** [thuyngch/ATSS-EfficientDet-PyTorch#6]
@thuyngch Thank you for sharing your great work!
Could you share the training time for D0/D1 with the setting (gpu, num gpu, cpu, etc..)?
Thanks,
Yuki

**Comment by thuyngch** [comment]
Hi @yukitsuji ,

I trained D0 with 300 epochs, 4 V100 GPUs.
You can find the detail config in here: https://github.com/thuyngch/ATSS-EfficientDet-PyTorch/blob/master/configs/effdet/atss_effdet_d0.py

**Comment by yukitsuji** [comment]
Thanks.
Could you also provide the log of D0 you trained, and the versions of mmcv and pytorch?
At the moment, I can not reproduce the map with the same setting. And It took over 2 days to train the D0 model.
